export const COMPETITIONS = {
    'premier-league': {
        sport: 'football',
        code: 'PL',
        name: 'Premier League',
        type: 'league',
        tier: 'free',
    },
    'champions-league': {
        sport: 'football',
        code: 'CL',
        name: 'UEFA Champions League',
        type: 'cup',
        tier: 'free',
    },
    'europa-league': {
        sport: 'football',
        code: 'EL',
        name: 'UEFA Europa League',
        type: 'cup',
        tier: 'paid',
    },
    'primera-division': {
        sport: 'football',
        code: 'PD',
        name: 'La Liga',
        type: 'league',
        tier: 'free',
    },
    'championship': {
        sport: 'football',
        code: 'ELC',
        name: 'Championship',
        type: 'league',
        tier: 'free',
    },
    'serie-a': {
        sport: 'football',
        code: 'SA',
        name: 'Serie A',
        type: 'league',
        tier: 'free',
    },
    'bundesliga': {
        sport: 'football',
        code: 'BL1',
        name: 'Bundesliga',
        type: 'league',
        tier: 'free',
    },
    'ligue-1': {
        sport: 'football',
        code: 'FL1',
        name: 'Ligue 1',
        type: 'league',
        tier: 'free',
    },
    'liga-portugal': {
        sport: 'football',
        code: 'PPL',
        name: 'Primeira Liga',
        type: 'league',
        tier: 'free',
    },
    'eredivisie': {
        sport: 'football',
        code: 'DED',
        name: 'Eredivise',
        type: 'league',
        tier: 'free',
    },
    'brasileirao': {
        sport: 'football',
        code: 'BSA',
        name: 'Brasileiro Série A',
        type: 'league',
        tier: 'free',
    },
    'fa-cup': {
        sport: 'football',
        code: 'FAC',
        name: 'FA Cup',
        type: 'cup',
        tier: 'paid',
    },
    'nba': {
        sport: 'basketball',
        code: 'nba',
        name: 'NBA',
        type: 'league',
        tier: 'free',
    },
};
